type: object
required: []
properties:
  disableDs:
    type: boolean
    default: false
    description: Disable `sds-node-configurator` DaemonSet.
  logLevel:
    type: string
    enum:
      - ERROR
      - WARN
      - INFO
      - DEBUG
      - TRACE
    description: Module application log level.
    default: INFO
  enableThinProvisioning:
    type: boolean
    default: true
    description: Enable support of thin LVM volumes.
