---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-tests
  namespace: d8-sds-node-configurator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-tests
rules:
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e2e-tests
subjects:
  - kind: ServiceAccount
    name: e2e-tests
    namespace: d8-sds-node-configurator
