---
apiVersion: deckhouse.io/v1alpha1
kind: KubeSchedulerWebhookConfiguration
metadata:
  name: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-common-scheduler-extender")) | nindent 2 }}
webhooks:
- weight: 5
  failurePolicy: Ignore
  clientConfig:
    service:
      name: sds-common-scheduler-extender
      namespace: d8-{{ .Chart.Name }}
      port: 8099
      path: /scheduler
    caBundle: {{ .Values.sdsNodeConfigurator.internal.customSchedulerExtenderCert.ca | b64enc }}
  timeoutSeconds: 5
